#!/bin/sh

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_COMMIT=$(git rev-parse HEAD)

# Get first 7 characters of commit hash
GIT_COMMIT_SHORT=$(echo $GIT_COMMIT | cut -c1-7)

TIMESTAMP=$(date +%s)

echo "$GIT_BRANCH-$GIT_COMMIT_SHORT-$TIMESTAMP"
